// <auto-generated />
using System;
using HaverDevProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaverDevProject.Data.HPMigrations
{
    [DbContext(typeof(HaverNiagaraContext))]
    partial class HaverNiagaraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("HaverDevProject.Models.Defect", b =>
                {
                    b.Property<int>("DefectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("defectId");

                    b.Property<string>("DefectName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("defectName");

                    b.HasKey("DefectId")
                        .HasName("pk_defect_defectId");

                    b.ToTable("defect");
                });

            modelBuilder.Entity("HaverDevProject.Models.Drawing", b =>
                {
                    b.Property<int>("DrawingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("drawingId");

                    b.Property<int>("DrawingOriginalRevNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drawingOriginalRevNumber");

                    b.Property<bool>("DrawingRequireUpdating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DrawingRequireUpdating");

                    b.Property<DateTime>("DrawingRevDate")
                        .HasColumnType("date")
                        .HasColumnName("drawingRevDate");

                    b.Property<int>("DrawingUpdatedRevNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drawingUpdatedRevNumber");

                    b.Property<int>("DrawingUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drawingUserId");

                    b.Property<int>("NcrEngId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ncrEngId");

                    b.HasKey("DrawingId")
                        .HasName("pk_drawing_drawingId");

                    b.HasIndex("NcrEngId")
                        .IsUnique();

                    b.ToTable("drawing");
                });

            modelBuilder.Entity("HaverDevProject.Models.EngDefectPhoto", b =>
                {
                    b.Property<int>("EngDefectPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("engDefectPhotoId");

                    b.Property<byte[]>("EngDefectPhotoContent")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("engDefectPhotoContent");

                    b.Property<string>("EngDefectPhotoDescription")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("engDefectPhotoDescription");

                    b.Property<string>("EngDefectPhotoMimeType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("engDefectPhotoMimeType");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrEngId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ncrEngId");

                    b.HasKey("EngDefectPhotoId")
                        .HasName("pk_engDefectPhoto_engDefectPhotoId");

                    b.HasIndex("NcrEngId");

                    b.ToTable("engDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.EngDispositionType", b =>
                {
                    b.Property<int>("EngDispositionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("engDispositionTypeId");

                    b.Property<string>("EngDispositionTypeName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("engDispositionTypeName");

                    b.HasKey("EngDispositionTypeId")
                        .HasName("pk_engDispoistionType_engDispositionTypeId");

                    b.ToTable("engDispositionType");
                });

            modelBuilder.Entity("HaverDevProject.Models.EngFileContent", b =>
                {
                    b.Property<int>("EngFileContentID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.HasKey("EngFileContentID");

                    b.ToTable("EngFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.FileContent", b =>
                {
                    b.Property<int>("FileContentID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.HasKey("FileContentID");

                    b.ToTable("FileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.FollowUpType", b =>
                {
                    b.Property<int>("FollowUpTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowUpTypeName")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("FollowUpTypeId")
                        .HasName("pk_followUpType_followUpTypeId");

                    b.ToTable("followUpType");
                });

            modelBuilder.Entity("HaverDevProject.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("itemId");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("itemName");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("itemNumber");

                    b.HasKey("ItemId")
                        .HasName("pk_item_itemId");

                    b.HasIndex("ItemNumber")
                        .IsUnique();

                    b.ToTable("item");
                });

            modelBuilder.Entity("HaverDevProject.Models.ItemDefectPhoto", b =>
                {
                    b.Property<int>("ItemDefectPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("itemDefectPhotoId");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ItemDefectPhotoContent")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("itemDefectPhotoContent");

                    b.Property<string>("ItemDefectPhotoDescription")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("itemDefectPhotoDescription");

                    b.Property<string>("ItemDefectPhotoMimeType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("itemDefectPhotoMimeType");

                    b.Property<int>("NcrQaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ncrQaId");

                    b.HasKey("ItemDefectPhotoId")
                        .HasName("pk_itemDefectPhoto_itemDefectPhotoId");

                    b.HasIndex("NcrQaId");

                    b.ToTable("itemDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.Ncr", b =>
                {
                    b.Property<int>("NcrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NcrLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrPhase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NcrStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrVoidReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NcrId")
                        .HasName("pk_ncr_ncrId");

                    b.HasIndex("ParentId");

                    b.ToTable("ncr");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrEng", b =>
                {
                    b.Property<int>("NcrEngId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrawingOriginalRevNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DrawingRequireUpdating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DrawingRevDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawingUpdatedRevNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrawingUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EngDispositionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NcrEngCompleteDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NcrEngCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrEngCustomerNotification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrEngDefectVideo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrEngDispositionDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrEngStatusFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrEngUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NcrPhase")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("NcrEngId")
                        .HasName("pk_ncrEng_ncrEngId");

                    b.HasIndex("EngDispositionTypeId");

                    b.HasIndex("NcrId")
                        .IsUnique();

                    b.ToTable("ncrEng");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrOperation", b =>
                {
                    b.Property<int>("NcrOpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Car")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FollowUpTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NcrEngId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NcrId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NcrOpCompleteDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NcrOpCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrOperationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrOperationVideo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrPurchasingDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpDispositionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdateOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("NcrOpId")
                        .HasName("pk_ncrOperation_ncrOpId");

                    b.HasIndex("FollowUpTypeId");

                    b.HasIndex("NcrEngId");

                    b.HasIndex("NcrId")
                        .IsUnique();

                    b.HasIndex("OpDispositionTypeId");

                    b.ToTable("NcrOperations");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrProcurement", b =>
                {
                    b.Property<int>("NcrProcurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NcrProcCompleteDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NcrProcCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrProcCreditExpected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrProcDefectVideo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrProcDisposedAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NcrProcExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrProcFlagStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NcrProcRejectedValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrProcSAPReturnCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NcrProcSupplierBilled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NcrProcSupplierReturnReq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrProcUserId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SupplierReturnAccount")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierReturnMANum")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierReturnName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("NcrProcurementId")
                        .HasName("pk_ncrProcurement_ncrProcurementId");

                    b.HasIndex("NcrId")
                        .IsUnique();

                    b.ToTable("NcrProcurements");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrQa", b =>
                {
                    b.Property<int>("NcrQaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NcrId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrQaDefectVideo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrQaDescriptionOfDefect")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrQaEngDispositionRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NcrQaItemMarNonConforming")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrQaOrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrQaProcessApplicable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NcrQaQuanDefective")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NcrQaQuanReceived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrQaSalesOrder")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrQaStatusFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrQaUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NcrQacreationDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("NcrQaId")
                        .HasName("pk_ncrQA_ncrQAId");

                    b.HasIndex("DefectId");

                    b.HasIndex("ItemId");

                    b.HasIndex("NcrId")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("ncrQA");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrReInspect", b =>
                {
                    b.Property<int>("NcrReInspectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NcrNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NcrQaStatusFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NcrReInspectAcceptable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NcrReInspectCompleteDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NcrReInspectCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrReInspectDefectVideo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrReInspectNewNcrNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrReInspectNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcrReInspectUserId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("NcrReInspectId")
                        .HasName("pk_ncrReInspect_ncrReInspectId");

                    b.HasIndex("NcrId")
                        .IsUnique();

                    b.ToTable("NcrReInspects");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrReInspectPhoto", b =>
                {
                    b.Property<int>("NcrReInspectPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ncrReInspectPhotoId");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrReInspectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ncrReInspectId");

                    b.Property<byte[]>("NcrReInspectPhotoContent")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("ncrReInspectPhotoContent");

                    b.Property<string>("NcrReInspectPhotoDescription")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("ncrReInspectPhotoDescription");

                    b.Property<string>("NcrReInspectPhotoMimeType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("ncrReInspectPhotoMimeType");

                    b.HasKey("NcrReInspectPhotoId")
                        .HasName("pk_ncrReInspectPhoto_ncrReInspectPhotoId");

                    b.HasIndex("NcrReInspectId");

                    b.ToTable("ncrReInspectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.OpDefectPhoto", b =>
                {
                    b.Property<int>("OpDefectPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("opDefectPhotoId");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrOpId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ncrOpId");

                    b.Property<byte[]>("OpDefectPhotoContent")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("opDefectPhotoContent");

                    b.Property<string>("OpDefectPhotoDescription")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("opDefectPhotoDescription");

                    b.Property<string>("OpDefectPhotoMimeType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("opDefectPhotoMimeType");

                    b.HasKey("OpDefectPhotoId");

                    b.HasIndex("NcrOpId");

                    b.ToTable("opDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.OpDispositionType", b =>
                {
                    b.Property<int>("OpDispositionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpDispositionTypeName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("OpDispositionTypeId")
                        .HasName("pk_opDispositionType_opDispositionTypeId");

                    b.ToTable("opDispositionType");
                });

            modelBuilder.Entity("HaverDevProject.Models.OpFileContent", b =>
                {
                    b.Property<int>("FileContentID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.HasKey("FileContentID");

                    b.ToTable("OpFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.ProcDefectPhoto", b =>
                {
                    b.Property<int>("ProcDefectPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("procDefectPhotoId");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NcrProcurementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ncrProcurementId");

                    b.Property<byte[]>("ProcDefectPhotoContent")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("procDefectPhotoContent");

                    b.Property<string>("ProcDefectPhotoDescription")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("procDefectPhotoDescription");

                    b.Property<string>("ProcDefectPhotoMimeType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("procDefectPhotoType");

                    b.HasKey("ProcDefectPhotoId")
                        .HasName("pk_procDefectPhoto_procDefectPhotoId");

                    b.HasIndex("NcrProcurementId");

                    b.ToTable("procDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.ProcFileContent", b =>
                {
                    b.Property<int>("ProcFileContentID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.HasKey("ProcFileContentID");

                    b.ToTable("ProcFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.ReInspectFileContent", b =>
                {
                    b.Property<int>("ReInspectFileContentID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .HasColumnType("BLOB");

                    b.HasKey("ReInspectFileContentID");

                    b.ToTable("ReInspectFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplierId");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplierCode");

                    b.Property<string>("SupplierContactName")
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplierContactName");

                    b.Property<string>("SupplierEmail")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplierEmail");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplierName");

                    b.Property<bool>("SupplierStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplierStatus");

                    b.HasKey("SupplierId")
                        .HasName("pk_supplier_supplierId");

                    b.HasIndex("SupplierCode")
                        .IsUnique();

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("HaverDevProject.Models.Drawing", b =>
                {
                    b.HasOne("HaverDevProject.Models.NcrEng", "NcrEng")
                        .WithOne("Drawing")
                        .HasForeignKey("HaverDevProject.Models.Drawing", "NcrEngId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NcrEng");
                });

            modelBuilder.Entity("HaverDevProject.Models.EngDefectPhoto", b =>
                {
                    b.HasOne("HaverDevProject.Models.NcrEng", "NcrEng")
                        .WithMany("EngDefectPhotos")
                        .HasForeignKey("NcrEngId")
                        .IsRequired()
                        .HasConstraintName("fk_engDefectPhoto_itemDefect");

                    b.Navigation("NcrEng");
                });

            modelBuilder.Entity("HaverDevProject.Models.EngFileContent", b =>
                {
                    b.HasOne("HaverDevProject.Models.EngDefectPhoto", "EngDefectPhoto")
                        .WithOne("EngFileContent")
                        .HasForeignKey("HaverDevProject.Models.EngFileContent", "EngFileContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EngDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.FileContent", b =>
                {
                    b.HasOne("HaverDevProject.Models.ItemDefectPhoto", "ItemDefectPhoto")
                        .WithOne("FileContent")
                        .HasForeignKey("HaverDevProject.Models.FileContent", "FileContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.ItemDefectPhoto", b =>
                {
                    b.HasOne("HaverDevProject.Models.NcrQa", "NcrQa")
                        .WithMany("ItemDefectPhotos")
                        .HasForeignKey("NcrQaId")
                        .IsRequired()
                        .HasConstraintName("fk_itemDefectPhoto_itemDefect");

                    b.Navigation("NcrQa");
                });

            modelBuilder.Entity("HaverDevProject.Models.Ncr", b =>
                {
                    b.HasOne("HaverDevProject.Models.Ncr", "ParentNcr")
                        .WithMany("ChildNcrs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ncr_parentId");

                    b.Navigation("ParentNcr");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrEng", b =>
                {
                    b.HasOne("HaverDevProject.Models.EngDispositionType", "EngDispositionType")
                        .WithMany("NcrEngs")
                        .HasForeignKey("EngDispositionTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_ncrEng_engDispositionType");

                    b.HasOne("HaverDevProject.Models.Ncr", "Ncr")
                        .WithOne("NcrEng")
                        .HasForeignKey("HaverDevProject.Models.NcrEng", "NcrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EngDispositionType");

                    b.Navigation("Ncr");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrOperation", b =>
                {
                    b.HasOne("HaverDevProject.Models.FollowUpType", "FollowUpType")
                        .WithMany("NcrOperations")
                        .HasForeignKey("FollowUpTypeId");

                    b.HasOne("HaverDevProject.Models.NcrEng", "NcrEng")
                        .WithMany()
                        .HasForeignKey("NcrEngId");

                    b.HasOne("HaverDevProject.Models.Ncr", "Ncr")
                        .WithOne("NcrOperation")
                        .HasForeignKey("HaverDevProject.Models.NcrOperation", "NcrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverDevProject.Models.OpDispositionType", "OpDispositionType")
                        .WithMany("NcrOperations")
                        .HasForeignKey("OpDispositionTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_ncrOperation_opDispositionType");

                    b.Navigation("FollowUpType");

                    b.Navigation("Ncr");

                    b.Navigation("NcrEng");

                    b.Navigation("OpDispositionType");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrProcurement", b =>
                {
                    b.HasOne("HaverDevProject.Models.Ncr", "Ncr")
                        .WithOne("NcrProcurement")
                        .HasForeignKey("HaverDevProject.Models.NcrProcurement", "NcrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ncr");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrQa", b =>
                {
                    b.HasOne("HaverDevProject.Models.Defect", "Defect")
                        .WithMany("NcrQas")
                        .HasForeignKey("DefectId")
                        .IsRequired()
                        .HasConstraintName("fk_ncrQa_defect");

                    b.HasOne("HaverDevProject.Models.Item", "Item")
                        .WithMany("NcrQas")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("fk_ncrQa_item");

                    b.HasOne("HaverDevProject.Models.Ncr", "Ncr")
                        .WithOne("NcrQa")
                        .HasForeignKey("HaverDevProject.Models.NcrQa", "NcrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HaverDevProject.Models.Supplier", "Supplier")
                        .WithMany("NcrQas")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("fk_ncrQa_supplier");

                    b.Navigation("Defect");

                    b.Navigation("Item");

                    b.Navigation("Ncr");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrReInspect", b =>
                {
                    b.HasOne("HaverDevProject.Models.Ncr", "Ncr")
                        .WithOne("NcrReInspect")
                        .HasForeignKey("HaverDevProject.Models.NcrReInspect", "NcrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ncr");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrReInspectPhoto", b =>
                {
                    b.HasOne("HaverDevProject.Models.NcrReInspect", "NcrReInspect")
                        .WithMany("NcrReInspectPhotos")
                        .HasForeignKey("NcrReInspectId")
                        .IsRequired()
                        .HasConstraintName("fk_ncrReInspectPhoto_itemDefect");

                    b.Navigation("NcrReInspect");
                });

            modelBuilder.Entity("HaverDevProject.Models.OpDefectPhoto", b =>
                {
                    b.HasOne("HaverDevProject.Models.NcrOperation", "NcrOperation")
                        .WithMany("OpDefectPhotos")
                        .HasForeignKey("NcrOpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NcrOperation");
                });

            modelBuilder.Entity("HaverDevProject.Models.OpFileContent", b =>
                {
                    b.HasOne("HaverDevProject.Models.OpDefectPhoto", "OpDefectPhoto")
                        .WithOne("OpFileContent")
                        .HasForeignKey("HaverDevProject.Models.OpFileContent", "FileContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.ProcDefectPhoto", b =>
                {
                    b.HasOne("HaverDevProject.Models.NcrProcurement", "NcrProcurement")
                        .WithMany("ProcDefectPhotos")
                        .HasForeignKey("NcrProcurementId")
                        .IsRequired()
                        .HasConstraintName("fk_procDefectPhoto_itemDefect");

                    b.Navigation("NcrProcurement");
                });

            modelBuilder.Entity("HaverDevProject.Models.ProcFileContent", b =>
                {
                    b.HasOne("HaverDevProject.Models.ProcDefectPhoto", "ProcDefectPhoto")
                        .WithOne("ProcFileContent")
                        .HasForeignKey("HaverDevProject.Models.ProcFileContent", "ProcFileContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcDefectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.ReInspectFileContent", b =>
                {
                    b.HasOne("HaverDevProject.Models.NcrReInspectPhoto", "NcrReInspectPhoto")
                        .WithOne("ReInspectFileContent")
                        .HasForeignKey("HaverDevProject.Models.ReInspectFileContent", "ReInspectFileContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NcrReInspectPhoto");
                });

            modelBuilder.Entity("HaverDevProject.Models.Defect", b =>
                {
                    b.Navigation("NcrQas");
                });

            modelBuilder.Entity("HaverDevProject.Models.EngDefectPhoto", b =>
                {
                    b.Navigation("EngFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.EngDispositionType", b =>
                {
                    b.Navigation("NcrEngs");
                });

            modelBuilder.Entity("HaverDevProject.Models.FollowUpType", b =>
                {
                    b.Navigation("NcrOperations");
                });

            modelBuilder.Entity("HaverDevProject.Models.Item", b =>
                {
                    b.Navigation("NcrQas");
                });

            modelBuilder.Entity("HaverDevProject.Models.ItemDefectPhoto", b =>
                {
                    b.Navigation("FileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.Ncr", b =>
                {
                    b.Navigation("ChildNcrs");

                    b.Navigation("NcrEng");

                    b.Navigation("NcrOperation");

                    b.Navigation("NcrProcurement");

                    b.Navigation("NcrQa");

                    b.Navigation("NcrReInspect");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrEng", b =>
                {
                    b.Navigation("Drawing");

                    b.Navigation("EngDefectPhotos");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrOperation", b =>
                {
                    b.Navigation("OpDefectPhotos");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrProcurement", b =>
                {
                    b.Navigation("ProcDefectPhotos");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrQa", b =>
                {
                    b.Navigation("ItemDefectPhotos");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrReInspect", b =>
                {
                    b.Navigation("NcrReInspectPhotos");
                });

            modelBuilder.Entity("HaverDevProject.Models.NcrReInspectPhoto", b =>
                {
                    b.Navigation("ReInspectFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.OpDefectPhoto", b =>
                {
                    b.Navigation("OpFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.OpDispositionType", b =>
                {
                    b.Navigation("NcrOperations");
                });

            modelBuilder.Entity("HaverDevProject.Models.ProcDefectPhoto", b =>
                {
                    b.Navigation("ProcFileContent");
                });

            modelBuilder.Entity("HaverDevProject.Models.Supplier", b =>
                {
                    b.Navigation("NcrQas");
                });
#pragma warning restore 612, 618
        }
    }
}
